CREATE (u1:User {id: "1", username: "user1", name: "User 1", createdAt: datetime(), password: "xyz", email: "1@example.com", avatar: "", bio: ""})
CREATE (u2:User {id: "2", username: "user2", name: "User 2", createdAt: datetime(), password: "xyz", email: "2@example.com", avatar: "", bio: ""})
CREATE (u3:User {id: "3", username: "user3", name: "User 3", createdAt: datetime(), password: "xyz", email: "3@example.com", avatar: "", bio: ""})
CREATE (u4:User {id: "4", username: "user4", name: "User 4", createdAt: datetime(), password: "xyz", email: "4@example.com", avatar: "", bio: ""})
CREATE (u1)-[:FOLLOWS]->(u3)
CREATE (u3)-[:FOLLOWS]->(u1)
CREATE (u2)-[:FOLLOWS]->(u4)
CREATE (u4)-[:FOLLOWS]->(u2)
CREATE (u1)-[:FOLLOWS]->(u4)
